### ISSUE TITLE
Run release job on tag publishing only (0.4.0-alpha.8 version)

### ISSUE THREAD

**Issue by grouzen** [zio/zio-sbt#222]
After switching to the latest alpha version I've noticed two release jobs running on the newly published tag. The second one failed in the release step because the artifacts have been published by the first one. 
The current condition is `if: ${{ github.event_name != 'pull_request' }}`. I believe, it should be changed to handle only tag pushes.

![Screenshot 2023-05-25 at 18-17-56 CI · zio_zio-telemetry@a5700b3](https://github.com/zio/zio-sbt/assets/278245/e0db4d74-f4ad-4b8a-aa88-294e89eeb166)

**Comment by grouzen** [comment]
Update:
In the latest release, the CI job was okay. But still, I'm wondering what is the purpose of running it?

**Comment by khajavi** [comment]
The `CI` job seems useless after the release event and we should remove that.

**Comment by guizmaii** [comment]
Fixed in https://github.com/zio/zio-sbt/releases/tag/v0.4.0-alpha.20
