### ISSUE TITLE
Remove the automatic dependency on zio

### ISSUE THREAD

**Issue by jivanic-demystdata** [zio/zio-sbt#410]
We need to remove the management of the ZIO dependency(ies) and version from this plugin.

zio-logging recently (v2.3.0) updated zio-sbt to the latest alpha version. 
This implicitly updated the ZIO version to `v2.1.1`, which isn't bin-compatible with `v2.0.x`

We had a bug a work because of that.

Dependencies version management must be explicit actions from the author of the libraries so that it's easier for the user of these lib to see/track when a dependency of these libs is updated.

I was quick to find the issue because I help on zio-sbt and I know quite well the ZIO env but I can't imagine how difficult it could be to find the issue when for more beginners 

Cc @khajavi

**Comment by devansh-m12** [comment]
@khajavi i would like to work on this issue please assign this to me
